### ISSUE TITLE
Easiest way to set the todo_keywords and done_keywords globally

### ISSUE THREAD

**Issue by lyz-code** [kenkeiras/org-rw#2]
I've seen that org-rw reads the todo_keywords and done_keywords from the files when loading them. I'm going to load many files that don't have that property set as I configure it at nvim-orgmode configuration level.

I've also dived through the code to see how to pass my custom values to the `load` function but it does not seem trivial. Which way would you do that? If you give me a sketch on how you'd like it I wouldn't mind creating a PR.

Thaaanks

**Comment by kenkeiras** [comment]
Addressed on: https://code.codigoparallevar.com/kenkeiras/org-rw/pulls/4

See new examples: https://github.com/kenkeiras/org-rw/blob/40d58d54889a03691065ff2122b6c47ada53c0e0/tests/test_org.py#L836-L849

We might want to consider a more structured (and less stringified) approach to this. We can add an alternate type to that `org-todo-keywords` which takes an appropriate structure.

**Comment by lyz-code** [comment]
Thanks!
